name: Scraper Concours Palet

on:
  schedule:
    - cron: '0 8 * * 0'  # Tous les dimanches à 8h
  workflow_dispatch:      # Permet de le lancer manuellement

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Installer Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-fra


      - name: Run scraper
        run: python scrape_concours.py

      - name: Commit and push CSV if exists
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          if [ -f concours_palet.csv ]; then
            git add concours_palet.csv
            git commit -m "Mise à jour automatique des concours" || true
            git push
          else
            echo "Aucun fichier concours_palet.csv à committer"
          fi

